# Generated by Django 2.1.5 on 2019-02-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KvmInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('state', models.BooleanField()),
                ('status', models.BooleanField()),
                ('password', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
