# Generated by Django 2.1.5 on 2019-02-20 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kvmcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvminfo',
            name='end_access',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
