# Generated by Django 2.1.5 on 2019-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvmcp', '0004_auto_20190222_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvminfo',
            name='end_access',
            field=models.BigIntegerField(null=True),
        ),
    ]
